export type Currencies = {
  STN: string,
  XAG: string,
  XAU: string,
  PLN: string,
  UGX: string,
  GGP: string,
  MWK: string,
  NAD: string,
  ALL: string,
  BHD: string,
  JEP: string,
  BWP: string,
  MRU: string,
  BMD: string,
  MNT: string,
  FKP: string,
  PYG: string,
  AUD: string,
  KYD: string,
  RWF: string,
  WST: string,
  SHP: string,
  SOS: string,
  SSP: string,
  BIF: string,
  SEK: string,
  CUC: string,
  BTN: string,
  MOP: string,
  XDR: string,
  IMP: string,
  INR: string,
  BYN: string,
  BOB: string,
  SRD: string,
  GEL: string,
  ZWL: string,
  EUR: string,
  BBD: string,
  RSD: string,
  SDG: string,
  VND: string,
  VES: string,
  ZMW: string,
  KGS: string,
  HUF: string,
  BND: string,
  BAM: string,
  CVE: string,
  BGN: string,
  NOK: string,
  BRL: string,
  JPY: string,
  HRK: string,
  HKD: string,
  ISK: string,
  IDR: string,
  KRW: string,
  KHR: string,
  XAF: string,
  CHF: string,
  MXN: string,
  PHP: string,
  RON: string,
  RUB: string,
  SGD: string,
  AED: string,
  KWD: string,
  CAD: string,
  PKR: string,
  CLP: string,
  CNY: string,
  COP: string,
  AOA: string,
  KMF: string,
  CRC: string,
  CUP: string,
  GNF: string,
  NZD: string,
  EGP: string,
  DJF: string,
  ANG: string,
  DOP: string,
  JOD: string,
  AZN: string,
  SVC: string,
  NGN: string,
  ERN: string,
  SZL: string,
  DKK: string,
  ETB: string,
  FJD: string,
  XPF: string,
  GMD: string,
  AFN: string,
  GHS: string,
  GIP: string,
  GTQ: string,
  HNL: string,
  GYD: string,
  HTG: string,
  XCD: string,
  GBP: string,
  AMD: string,
  IRR: string,
  JMD: string,
  IQD: string,
  KZT: string,
  KES: string,
  ILS: string,
  LYD: string,
  LSL: string,
  LBP: string,
  LRD: string,
  AWG: string,
  MKD: string,
  LAK: string,
  MGA: string,
  ZAR: string,
  MDL: string,
  MVR: string,
  MUR: string,
  MMK: string,
  MAD: string,
  XOF: string,
  MZN: string,
  MYR: string,
  OMR: string,
  NIO: string,
  NPR: string,
  PAB: string,
  PGK: string,
  PEN: string,
  ARS: string,
  SAR: string,
  QAR: string,
  SCR: string,
  SLL: string,
  LKR: string,
  SBD: string,
  VUV: string,
  USD: string,
  DZD: string,
  BDT: string,
  BSD: string,
  BZD: string,
  CDF: string,
  UAH: string,
  YER: string,
  TMT: string,
  UZS: string,
  UYU: string,
  CZK: string,
  SYP: string,
  TJS: string,
  TWD: string,
  TZS: string,
  TOP: string,
  TTD: string,
  THB: string,
  TRY: string,
  TND: string,
}

enum CURRENCY {
  STN = 'STN',
  XAG = 'XAG',
  XAU = 'XAU',
  PLN = 'PLN',
  UGX = 'UGX',
  GGP = 'GGP',
  MWK = 'MWK',
  NAD = 'NAD',
  ALL = 'ALL',
  BHD = 'BHD',
  JEP = 'JEP',
  BWP = 'BWP',
  MRU = 'MRU',
  BMD = 'BMD',
  MNT = 'MNT',
  FKP = 'FKP',
  PYG = 'PYG',
  AUD = 'AUD',
  KYD = 'KYD',
  RWF = 'RWF',
  WST = 'WST',
  SHP = 'SHP',
  SOS = 'SOS',
  SSP = 'SSP',
  BIF = 'BIF',
  SEK = 'SEK',
  CUC = 'CUC',
  BTN = 'BTN',
  MOP = 'MOP',
  XDR = 'XDR',
  IMP = 'IMP',
  INR = 'INR',
  BYN = 'BYN',
  BOB = 'BOB',
  SRD = 'SRD',
  GEL = 'GEL',
  ZWL = 'ZWL',
  EUR = 'EUR',
  BBD = 'BBD',
  RSD = 'RSD',
  SDG = 'SDG',
  VND = 'VND',
  VES = 'VES',
  ZMW = 'ZMW',
  KGS = 'KGS',
  HUF = 'HUF',
  BND = 'BND',
  BAM = 'BAM',
  CVE = 'CVE',
  BGN = 'BGN',
  NOK = 'NOK',
  BRL = 'BRL',
  JPY = 'JPY',
  HRK = 'HRK',
  HKD = 'HKD',
  ISK = 'ISK',
  IDR = 'IDR',
  KRW = 'KRW',
  KHR = 'KHR',
  XAF = 'XAF',
  CHF = 'CHF',
  MXN = 'MXN',
  PHP = 'PHP',
  RON = 'RON',
  RUB = 'RUB',
  SGD = 'SGD',
  AED = 'AED',
  KWD = 'KWD',
  CAD = 'CAD',
  PKR = 'PKR',
  CLP = 'CLP',
  CNY = 'CNY',
  COP = 'COP',
  AOA = 'AOA',
  KMF = 'KMF',
  CRC = 'CRC',
  CUP = 'CUP',
  GNF = 'GNF',
  NZD = 'NZD',
  EGP = 'EGP',
  DJF = 'DJF',
  ANG = 'ANG',
  DOP = 'DOP',
  JOD = 'JOD',
  AZN = 'AZN',
  SVC = 'SVC',
  NGN = 'NGN',
  ERN = 'ERN',
  SZL = 'SZL',
  DKK = 'DKK',
  ETB = 'ETB',
  FJD = 'FJD',
  XPF = 'XPF',
  GMD = 'GMD',
  AFN = 'AFN',
  GHS = 'GHS',
  GIP = 'GIP',
  GTQ = 'GTQ',
  HNL = 'HNL',
  GYD = 'GYD',
  HTG = 'HTG',
  XCD = 'XCD',
  GBP = 'GBP',
  AMD = 'AMD',
  IRR = 'IRR',
  JMD = 'JMD',
  IQD = 'IQD',
  KZT = 'KZT',
  KES = 'KES',
  ILS = 'ILS',
  LYD = 'LYD',
  LSL = 'LSL',
  LBP = 'LBP',
  LRD = 'LRD',
  AWG = 'AWG',
  MKD = 'MKD',
  LAK = 'LAK',
  MGA = 'MGA',
  ZAR = 'ZAR',
  MDL = 'MDL',
  MVR = 'MVR',
  MUR = 'MUR',
  MMK = 'MMK',
  MAD = 'MAD',
  XOF = 'XOF',
  MZN = 'MZN',
  MYR = 'MYR',
  OMR = 'OMR',
  NIO = 'NIO',
  NPR = 'NPR',
  PAB = 'PAB',
  PGK = 'PGK',
  PEN = 'PEN',
  ARS = 'ARS',
  SAR = 'SAR',
  QAR = 'QAR',
  SCR = 'SCR',
  SLL = 'SLL',
  LKR = 'LKR',
  SBD = 'SBD',
  VUV = 'VUV',
  USD = 'USD',
  DZD = 'DZD',
  BDT = 'BDT',
  BSD = 'BSD',
  BZD = 'BZD',
  CDF = 'CDF',
  UAH = 'UAH',
  YER = 'YER',
  TMT = 'TMT',
  UZS = 'UZS',
  UYU = 'UYU',
  CZK = 'CZK',
  SYP = 'SYP',
  TJS = 'TJS',
  TWD = 'TWD',
  TZS = 'TZS',
  TOP = 'TOP',
  TTD = 'TTD',
  THB = 'THB',
  TRY = 'TRY',
  TND = 'TND',
}

type CurrencyCode = keyof typeof CURRENCY

type BasicConversion = {
  base_currency_code: string,
  base_currency_name: string,
  amount: string,
  updated_date: string
}

type Currency = {
  currency_name: string,
  rate: string
  rate_for_amount: string
}

export type Conversion = BasicConversion & Record<CurrencyCode, Currency>

